"""
Contact Service - Business Logic Layer
Handles contact form submissions
"""
from typing import Optional
from app.models import ContactMessage
from app.repositories import IContactRepository
from app.schemas import ContactFormSubmit, ContactFormResponse


class ContactService:
    """
    Service for contact form operations
    Contains business logic for handling contact messages
    """
    
    def __init__(self, contact_repository: IContactRepository, email_service=None):
        self._repository = contact_repository
        self.email_service = email_service
    
    def submit_contact_form(self, restaurant_id: str, form_data: ContactFormSubmit) -> ContactFormResponse:
        """
        Process contact form submission
        In a real application, this might also send an email notification
        """
        # Create contact message entity
        message = ContactMessage(
            id=None,  # Will be generated by repository
            restaurant_id=restaurant_id,
            name=form_data.name,
            email=form_data.email,
            subject=form_data.subject,
            message=form_data.message,
        )
        
        # Save message
        saved_message = self._repository.create(message)
        
        # Send notification email to restaurant (non-blocking - don't fail if email fails)
        if self.email_service:
            try:
                # Format phone number - handle both with and without phone field
                phone = getattr(form_data, 'phone', 'Not provided')
                
                self.email_service.send_contact_form_notification(
                    customer_name=form_data.name,
                    customer_email=form_data.email,
                    customer_phone=phone,
                    message_text=f"Subject: {form_data.subject}\n\n{form_data.message}"
                )
            except Exception as e:
                # Log error but don't fail the form submission
                print(f"⚠️  Failed to send contact form notification: {str(e)}")
        
        return ContactFormResponse(
            success=True,
            message="Message sent! We will get back to you soon."
        )
    
    def get_all_messages(self):
        """Get all contact messages (admin function)"""
        return self._repository.get_all()
    
    def get_message(self, message_id: str) -> ContactMessage | None:
        """Get a specific contact message by ID"""
        return self._repository.get_by_id(message_id)

