"""
Contact Service - Business Logic Layer
Handles contact form submissions
"""
from app.models import ContactMessage
from app.repositories import IContactRepository
from app.schemas import ContactFormSubmit, ContactFormResponse


class ContactService:
    """
    Service for contact form operations
    Contains business logic for handling contact messages
    """
    
    def __init__(self, contact_repository: IContactRepository):
        self._repository = contact_repository
    
    def submit_contact_form(self, restaurant_id: str, form_data: ContactFormSubmit) -> ContactFormResponse:
        """
        Process contact form submission
        In a real application, this might also send an email notification
        """
        # Create contact message entity
        message = ContactMessage(
            id=None,  # Will be generated by repository
            restaurant_id=restaurant_id,
            name=form_data.name,
            email=form_data.email,
            subject=form_data.subject,
            message=form_data.message,
        )
        
        # Save message
        saved_message = self._repository.create(message)
        
        # In a real application, you might:
        # - Send an email to the restaurant
        # - Send a confirmation email to the customer
        # - Trigger a notification to staff
        
        return ContactFormResponse(
            success=True,
            message="Message sent! We will get back to you."
        )
    
    def get_all_messages(self):
        """Get all contact messages (admin function)"""
        return self._repository.get_all()
    
    def get_message(self, message_id: str) -> ContactMessage | None:
        """Get a specific contact message by ID"""
        return self._repository.get_by_id(message_id)

