"""
Reservation Service - Business Logic Layer
Handles reservation-related business operations
"""
from app.models import Reservation
from app.repositories import IReservationRepository
from app.schemas import ReservationCreate, ReservationConfirmation
from datetime import datetime


class ReservationService:
    """
    Service for reservation operations
    Contains business logic for handling reservations
    """
    
    def __init__(self, reservation_repository: IReservationRepository):
        self._repository = reservation_repository
    
    def create_reservation(self, restaurant_id: str, reservation_data: ReservationCreate) -> ReservationConfirmation:
        """
        Create a new reservation
        Includes business logic validation
        """
        # Validate reservation date is not in the past
        try:
            reservation_date = datetime.strptime(reservation_data.date, "%Y-%m-%d")
            if reservation_date.date() < datetime.now().date():
                raise ValueError("Cannot make reservations for past dates")
        except ValueError as e:
            if "does not match format" in str(e):
                raise ValueError("Invalid date format. Use YYYY-MM-DD")
            raise
        
        # Validate time format
        try:
            datetime.strptime(reservation_data.time, "%H:%M")
        except ValueError:
            raise ValueError("Invalid time format. Use HH:MM (24-hour format)")
        
        # Create reservation entity
        reservation = Reservation(
            id=None,  # Will be generated by repository
            restaurant_id=restaurant_id,
            name=reservation_data.name,
            email=reservation_data.email,
            phone=reservation_data.phone,
            date=reservation_data.date,
            time=reservation_data.time,
            party_size=reservation_data.party_size,
            special_requests=reservation_data.special_requests,
        )
        
        # Save reservation
        saved_reservation = self._repository.create(reservation)
        
        return ReservationConfirmation(
            success=True,
            message="Reservation confirmed! See you soon.",
            reservation_id=saved_reservation.id
        )
    
    def get_reservation(self, reservation_id: str) -> Reservation | None:
        """Get a specific reservation by ID"""
        return self._repository.get_by_id(reservation_id)
    
    def get_all_reservations(self):
        """Get all reservations (admin function)"""
        return self._repository.get_all()
    
    def cancel_reservation(self, reservation_id: str) -> bool:
        """Cancel a reservation"""
        return self._repository.delete(reservation_id)

