"""Add restaurant and menu items tables

Revision ID: 1e85fe77f2e9
Revises: 48038e2b4f4d
Create Date: 2025-10-28 11:04:54.059272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e85fe77f2e9'
down_revision: Union[str, None] = '48038e2b4f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_restaurant_id'), 'chat_messages', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_restaurant_session', 'chat_messages', ['restaurant_id', 'session_id'], unique=False)
    op.create_index('ix_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_created', table_name='chat_messages')
    op.drop_index('ix_restaurant_session', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_restaurant_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    # ### end Alembic commands ###
